CodeSystem: CSPainNRS
Title: "Pain Numeric Rating Scale (NRS)評估量表代碼系統"
Description: "Pain Numeric Rating Scale (NRS)評估量表代碼系統，用於表示疼痛強度的數值評分。"
* #0 "無痛"
* #1 "輕微痛"
* #2 "輕微痛"
* #3 "輕微痛"
* #4 "中度疼痛"
* #5 "中度疼痛"
* #6 "中度疼痛"
* #7 "嚴重疼痛"
* #8 "嚴重疼痛"
* #9 "嚴重疼痛"
* #10 "嚴重疼痛"
